Dev
VladimirShtefan/Lesson_17_HW_Flask_REST pull request #2
Opened 2022-08-08 14:43 UTC by VladimirShtefan

2022-08-08 19:36 UTC, painassasin requested changes

2022-08-08 19:36 UTC, painassasin commented on app/api/api_models/movies.py
> +movie_model = api.model(
Я думаю можно было все модели в один файл положить, они все таки очень связаны, не вижу необходимости делить

2022-08-08 19:36 UTC, painassasin commented on app/api/api_models/movies.py
> +        'year': fields.Integer(),
min=0

2022-08-08 19:36 UTC, painassasin commented on app/api/api_models/movies.py
> +        'rating': fields.Float(),
min=0.0, max=10.0

2022-08-08 19:36 UTC, painassasin commented on app/app.py
> +if os.environ.get('FLASK_ENV', 'development'):
Тут по хорошему, если не указана переменная окружения, вообще запускать не давать
```python
# python 3.10
match os.environ.get('FLASK_ENV'):
     case 'development':
         app.config.from_object(DevConfig)
     case 'production':
         app.config.from_object(ProdConfig)
      case _:
           raise RuntimeError('Need to set environment variable \'FLASK_ENV\'')

2022-08-08 19:36 UTC, painassasin commented on app/constants.py
> +DATA_BASE_PATH = Path.joinpath(CURRENT_PATH, 'data_base', 'test.db')
А зачем базу в отдельную папку класть?)

2022-08-08 19:36 UTC, painassasin commented on app/dao/base_dao.py
> +    def get_all(self) -> list[DefaultMeta]:
Немного кривой тайпхинт, тут лучше попробовать использовать дженерики
```python
T = TypeVar('T', bound=DefaultMeta)   # Возможно кст тут не тот bound, но можно и без него попробовать

class BaseDAO(Generic[T]):
     def get_all(self) -> list[T]
         ...
         
class DirectorDAO(BaseDAO[Director]):
     ...
 ```

2022-08-08 19:36 UTC, painassasin commented on app/dao/base_dao.py
> +    def get_all(self) -> list[DefaultMeta]:
Немного кривой тайпхинт, тут лучше попробовать использовать дженерики
```python
T = TypeVar('T', bound=DefaultMeta)   # Возможно кст тут не тот bound, но можно и без него попробовать

class BaseDAO(Generic[T]):
     def get_all(self) -> list[T]
         ...
         
class DirectorDAO(BaseDAO[Director]):
     ...
 ```

2022-08-08 19:36 UTC, painassasin commented on app/dao/base_dao.py
> +    def get_one_by_id(self, id: int):
Не забывай про тайпхинты

2022-08-08 19:36 UTC, painassasin commented on app/dao/directors_dao.py
> +        director: Director = self.get_one_by_id(mid)
получить модель, обновить модель - два запроса - зачем?
почитай на sqlalchemy как можно делать update запрос по человечески)

2022-08-08 19:36 UTC, painassasin commented on app/dao/models/directors.py
> +    name = db.Column(db.String(255))
Давай добавим уникальность для поля name у Режиссера и Жанра - выглядит логичным

2022-08-08 19:36 UTC, painassasin commented on app/dao/models/movies.py
> +    __tablename__ = 'movie'
Нужно два констрейнта (условия) - на год и на рейтинг, пример
```python
__table_args__ = (
        db.Constraint('year > 0'),
 )

2022-08-08 19:36 UTC, painassasin commented on app/dao/movie_dao.py
> +        director_id = data.get('director_id')
Не очень удобно передавать это словарем (¯\_(ツ)_/¯ есть ли там ключи или нет) - тут по хорошему отдавать переменные в параметрах функции или каком-нибудь классе-объекте и функция должна возвращать список (даже пустой сканает)

2022-08-08 19:36 UTC, painassasin commented on app/views/directors.py
> +        return BaseDAO(Director).get_all(), 200
Почему тут вызвается BaseDAO, а не DIrectorDAO??
BaseDAO - должен быть просто родителем, общим интерфейсом, но не более того, использовать нужно конкретный класс

2022-08-08 19:36 UTC, painassasin commented on app/views/movies.py
> +        result = MovieDAO(Movie).filter_movies(data)
Это че за странный прикол?)
Должен быть только один запрос в базу, в любом случае, указаны ли параметры фильтрации или нет

2022-08-08 19:36 UTC, painassasin commented on run.py
> +    os.environ['FLASK_ENV'] = 'development'
В проде не допустимо. Лучше в readme указать, что для запуска проекта нужна эта переменная. Вообще все что касается запуска лучше указать в readme

2022-08-09 01:22 UTC, VladimirShtefan commented on app/api/api_models/movies.py
> +movie_model = api.model(
Это было сделано согласно шпаргалки https://skyengpublic.notion.site/18-2-f9747c5482984b8a9802fff832fd3074
Исправлю.

2022-08-09 01:24 UTC, VladimirShtefan commented on app/constants.py
> +DATA_BASE_PATH = Path.joinpath(CURRENT_PATH, 'data_base', 'test.db')
Это тестовая база я решил положить её рядом с файлом для создания этой тестовой базы и рядом с данными из которых она формируется

2022-08-09 15:00 UTC, painassasin requested changes

2022-08-09 15:00 UTC, painassasin commented on app/dao/models/genres.py
> +    __tablename__ = 'director'
Класс Genre, а табличка director

2022-08-09 15:00 UTC, painassasin commented on app/dao/base_dao.py
> +    __model__ = ABCMeta
Чет я не уверен, что тут `ABCMeta` должна быть, может хотя бы `db.Model`?

2022-08-09 16:01 UTC, painassasin approved these changes

2022-08-09 16:41 UTC, merged